emacs-lsp/dap-mode

dap-java.el

I'm basing this on https://github.com/emacs-lsp/lsp-java/blob/bfab7a684152d6d424708221fa1200dff7edfc20/lsp-java.el#L527
Whereas in dap-java, we are looking for a directory called `runner`

The default dir for the test runner is test-runner in lsp-java

---

dap-ui-repl.el

There was an error after selecting a candidate:
```company-call-backend-raw: Company: backend company-dap-ui-repl error
"Wrong type argument: char-or-string-p, nil" with args (post-completion long_name)```

Fix an error with repl completions in python

---

dap-mode.el

This PR does the following:
- Remove an unused `workspace` let binding.
- Require `cl` in `dap-mode`, as it uses `first` and `rest` and a user may receive a `Symbol's function definition is void: first` error message when running `dap-debug` otherwise.

Two small code fixes

---

README.org

Also, s/It similar/It's similar/ and add the note about requiring lsp
mode to separate line.
Every contribution counts :)

Remove duplicate link to DAP page in README

---

dap-lldb.el

Hello
It is not work to get the path of debugging file with `buffer-file-name` in c/c++ mode.So I added a variable to let the user customize the function.

Add a variable to get the debug file path 

---

README.org
dap-php.el

This works only  'kind-of'; sessions-list shows weird behaviour; company-completion in repl does not work; and a few other minor things.
But I can debug with xdebug :) 
I have my setup so that I don't need a path-mapping, paths are equal remote/local, but it should be easy to add to the debug template.

Preliminary support for felixbecker/vscode-php-debug

---

dap-python.el

In some cases, people's python executable is not `python`; it can be `python3`, `pyenv exec python` or others.

Add custom python executable

---

dap-python.el

A recent commit #39 broke the Python dap-mode configuration. 
```
python -m ptvsd --wait --host python --port localhost 32000
Error: invalid --port <port>: invalid literal for int() with base 10: 'localhost'
```
I believe it is this line which causes the error: https://github.com/yyoncho/dap-mode/blob/46e1e9d5b2dd94d7044f8fac912877b6c2f6728d/dap-python.el#L49
There is an additional `dap-python-executable` in the arguments, which causes it.

Fix ptvsd format arguments

---

README.org
dap-php.el

Hmm -- don't know why the 23.Jan commits are included here...
Fix the `:type` error (`php`, not `node`)

Tomterl fix type

---

dap-java.el
dap-mode.el
dap-ui.el

In order to solve #44 and (some problem of) #44 , https://github.com/yyoncho/dap-mode/commit/ebb34c394067c81e29a36dc71452f326319a782d introduces `(require 'cl)` outside of `eval-when-compile`, which causes complain from linter.
[Emacs recommands](https://www.gnu.org/software/emacs/manual/html_mono/cl.html#Organization) `cl-lib` instead of `cl` for new packages. However, functions provided by `cl-lib` are prefixed with 'cl-' (which provides some kind of namespace), so switching to `cl-lib` requires prepending this prefix to functions from `cl`.
After changing `cl` to `cl-lib` (restart emacs, `features` shows that `cl` is not loaded), all unknown symbols ( `first`, `second`, `rest`, `for`, `let*`) reported by `byte-recompile-directory` are changed to their `cl-lib` counterpart (`cl-first`, …

dap-mode.el: use cl-lib instead of cl

---

dap-mode.el

A click on the left margin or fringe will add a DAP breakpoint if
`dap-mode` minor mode is also enabled.
In the future, when enabling/disabling breakpoints is implemented,
this could toggle between creating, and then enabling/disabling
breakpoints, with another mouse event (ie, right click?) reserved for
removing a breakpoint.

Add support for setting and removing breakpoints using the mouse

---

dap-java.el

I was trying out `dap-mode` with java
and simply run `dap-debug` with compile and attach.

Fix dap-java compile and attach

---

dap-python.el

- Omits arguments blocks all applications that require positonal
arguments to be debugged.

Forward configured arguments to python debugger.

---

dap-mode.el
dap-ui.el

Since `dap--initialize-message` is using `pathFormat` with `path` instead of `uri`, parser side should stop call lsp--uri-to-path too. Else we will have a throw.
``` elisp
(list :command "initialize"
:arguments (list :clientID "vscode"
:clientName "Visual Studio Code"
:adapterID adapter-id
:pathFormat "path"
:linesStartAt1 t
:columnsStartAt1 t
:supportsVariableType t
:supportsVariablePaging t
:supportsRunInTerminalRequest t
:locale "en-us")
:type "request")
```

Don't call lsp--uri-to-path since pathFormat is path

---

dap-go.el

This PR does:
- Fix misc errors in dap-go.el
- Set `dap-go-delve-path` to `(executable-find "dlv")` instead of hard-coded path to linux binary. Which will make it works cross-platform.
- Change some tabs to spaces
- Adding debug-attach configuration to dap-go. It will ask user port and remote process that needed to attach to.

Adding debug-attach configuration for dap-go.el

---

README.org
dap-chrome.el
dap-firefox.el
dap-gdb-lldb.el
dap-go.el
dap-php.el
dap-ruby.el
dap-utils.el

Instead of having manually download the `VsCode` extensions, we should be able to automatically/effortlessly download those extensions right from `Emacs`.
This changes provided:
- `dap-utils-get-vscode-extension` to download `VsCode` extension to specified path.
- Update `dap-chrome`, `dap-firefox`, `dap-gdb-llb`, `dap-go`, `dap-php` and `dap-ruby` to leverage new utilities function.
- Create new `dap-go-setup` series of command to download `VsCode` extension.

Add command to download vscode bits

---

dap-mode.el

According to the spec, "path" is an optional property of a Source, so
in some cases, stack frames may have a "source" but no "path"
inside (for example, if the stack frame is OS library code). We now
only try to open a source file if there is a path attached.
Previously, in those cases we tried to execute `(find-file nil)`, which 
aborted the program.

Only navigate to source files if we have a path

---

dap-mode.el

Calling `file-exists-p` with a `nil` argument throws `Wrong type argument: stringp, nil`.

Protect file-exists-p call against nil arguments

---

README.org
dap-edge.el

Add js debugger using Microsoft Edge. It's similar to Chrome and Firefox

Add jsdebugger using Microsoft Edge

---

dap-ui.el

Remove B and E from the documentation, as the parameters were
refactored recently.
If the point is not a mark or an integer, bail without creating an
overlay.

Protect dap-ui--make-overlay-at if the point is nil

---

dap-php.el

The server port isn't set this way.  The line is a remnant of the trial and error phase of setting up php debugging.

Remove unnecessary config element

---

dap-php.el

Sometimes (mostly when debugging command-line tools), I don't want to/can set a breakpoint, but just want to enter the debugger from the start.  This resembles gebens default behaviour, IIRC.

Add 'stop on entry' debugging template for php

---

dap-mode.el

I am pretty new to this project, so feedback is greatly appreciated! Thanks 
closes #120 
- When debugging an application (nodejs in my case), it is difficult to distinguish stdout from other DAP output in the output buffer. See #120 
- The output buffer did not scroll when new output was printed to the buffer.
You can now use the custom `dap-output-buffer-filter` to filter the output based on the categories you want to see. I have set the default as "stdout", because I thought that the telemetry output such as "FullSessionStatistics/SourceMaps/Overrides" was not very helpful when debugging a program.
Result:
Consider this simple program
```nodejs
for (let i = 0; i < 10; i++) {
console.log(i);
}
```
With `dap-output-buffer-filter` set to `'("stdout")`, the output buffer now produces this …

filter output buffer, label by category, and add output buffer scrolling

---

dap-mode.el
dap-ui.el

In multibyte character environment, the breakpoints can be unusable for two reasons:
1. If there are multibyte characters in source code, the breakpoints will be shifted upward (see screenshot below)
2. If file path includes multibyte characters (e.g. `~/あいう/src/main.rs`), the breakpoints cannot be read from .dap-breakpoints
I confirmed these problem are caused by insert-file-contents-literally() and can be resolved by using insert-file-contents() instead.

Fix breakpoints broken in multibyte character environment

---

dap-mode.el

At the moment, `dap-mode` presents an error message if the containing directory doesn't exist.

Create the breakpoint file's directory if it doesn't exist.

---

README.org
dap-pwsh.el

I'm the author of [lsp-powershell](https://github.com/kiennq/lsp-powershell) and would like to move it under the umbrella of lsp-mode.

Moving dap-pwsh from kiennq/dap-pwsh

---

dap-mode.el

Deriving from compilation-mode in the server-log buffer adds syntax highlighting and links for error stacktraces

Derive dap-server-log-mode from compilation-mode for stacktrace highlighting and links

---

dap-mode.el

Before:
After:
I also made these buffers read-only.

Render ansi colors in output buffers

---

dap-ui.el

Posframe is not a package dependency of dap-mode. If this package is not installed, `dap-ui-controls-mode` was still registering some hooks that depended on posframe and caused type errors because of `void` function definitions.

Do not toggle dap-ui-controls-mode if posframe is not installed

---

dap-java.el

After changes to 'defcustom lsp-server-install-dir' in 'lsp-mode'
and 'defcustom lsp-java-server-install-dir' in 'lsp-java', 'dap-java'
cannot successfully derive the test runner jar file.
This change fixes that by concatenating the variable
'lsp-java-server-install-dir' with the relative path where the junit
test runner jar file is expected to be found.

Fix the derivation of defcustom dap-java-test-runner.

---

README.org

Description for `dap-breakpoint-add` says `Add java breakpoint at line`, which seems to be a mistake because it is not tied to Java language.

Removed java mentioning from breakpoint description

---

dap-ui.el

When posframe is installed but not required yet
`(fboundp 'posframe-show)` returns `t` because it's autoloaded
but posframe-hide is not autoloaded (because it doesn't make sense)
and therefore `(fboundp 'posframe-show)` returns `nil`
which then wrongly complains that I need `posframe` installed.

Fix test if posframe is installed

---

README.org
dap-ruby.el

I got this error and found out that the path to main.js has been changed.
```
Error: Cannot find module '/Users/snowflake/.emacs.d/.local/etc/dap-extension/vscode/rebornix.Ruby/extension/out/debugger/main.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
at Function.Module._load (internal/modules/cjs/loader.js:864:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at internal/main/run_main_module.js:18:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
```

update the new path to main.js

---

dap-mode.el

In `lsp-dart` we need to ask/setup the emulator for `Flutter` when user chooses to `dap-debug`, so this adds support for async debug.
Confirmed that works with `dap-debug`, `dap-debug-last`, `dap-debut-recent` and `dap-debug-restart`.

Add support for async conf

---

dap-ui.el

The padding missing it was really annoying me, sorry :sweat_smile: 
Before:
After:

Improve dap-ui-controls ui

---

dap-ui.el

The problem is that when `buffer-file-name` from [here](https://github.com/emacs-lsp/dap-mode/blob/master/dap-ui.el#L463) returns a symlink, it will build a invalid path for the icons.

Fix absolute path for icons when using symlink files

---

dap-mode.el
dap-ui.el
docs/page/configuration.md
docs/page/how-to.md

This adds an option to auto-configure `dap-mode` and `dap-ui-mode` to have a more "Emacs as IDE" behavior.

Add auto configuration mode

---

dap-mode.el
dap-ui.el

This removed a bunches of warning when byte-compile `dap-mode`.
There's still warnings under `dap-python.el`, but I assume @adam-r-kowalski is working on that, so put it on hold.

cleanup: fix bunches of warnings when byte-compile

---

dap-java.el
dap-mode.el
dap-ui.el

`dap-ui-sessions-mode` and `dap-ui-breakpoints-mode` are local mode that should only be enabled in special buffer, right now we enabled it together with `dap-auto-configure-mode`, which cause wrong mode and key bindings enabled in edit buffer. We should fix that.
One example is enabled `dap-auto-configure-mode` in `*scratch*` buffer, and we cannot type `D` anymore, since it's interfere with `dap-ui-breakpoints-mode` key bindings.
Also, fix several byte compile warnings.

dap-feature->modes: remove buffer local mode

---

dap-mode.el

Display `dap-mode-line` even after the session is failed or terminated is a huge waste on `mode-line` area. We should only display it when the debugger is running.
And hide it when it's terminated/failed.

dap-mode-line: dont display when failed or terminated

---

page/configuration/index.html

The old repository is obsolete and the code doesn't compile anymore with llvm-10

Update link to lldb-vscode

---

dap-mode.el

Sets the output buffer to read only and allows quitting by pressing
`q` which makes for a nice dev workflow, as you switch back to the
buffer where you started rather than having to manually kill the
buffer and navigate back.
For more info on special-mode: https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html
An improvement on this could be to define a new major mode for output buffers so we can build upon this and provide some better defaults, the behaviour with my change enables quitting the window but the buffer remains, ideally I think the buffer should be killed as well, as when running unit tests you can end up with a lot of obsolete buffers.

Use special-mode for the output buffer so `q` can be used to quit

---

dap-mode.el

output buffer now follows when new output is added

fix regression for window-point-insertion-type=t being overwritten

---

dap-ui.el

I found myself wanting a function that always prompts for an expression to add. dap-ui-expressions-add uses either the selected text, or (thing-at-point), but never prompts. dap-ui-expressions-add-prompt always prompts the user if called interactively.

Add an always prompting version of dap-ui-expressions-add

---

dap-mode.el
dap-variables.el

Variable blocks ${...} can now be escaped. \${...} always becomes ${...}.
Additionally, '}' can now be escaped in variable blocks. Previously, there was
no way to refer to a 'env:}' variable, for example. Now, this can be done with
${env:\}}.
All variable-related regular expressions now require that the entire variable
match. Previously, ${workspaceFolderFooBar} was equivalent to
${workspaceFolder}. Fix this, throwing an error in that case.
The ${env:...} variable had a bug causing a strange error to be thrown if the
environment variable references did not exist. Fix this, making it warn and
return the empty string instead.
There is still more to come in this feature branch, including support for numbered prompting variables. However, this commit contains a bug-fix, so you may want to …

Add escaping; stricter variable regexes; fix env: bug

---

dap-launch.el
tests/dap-launch-test.el

Implement #339. Already supports .vscode/launch.json files (tested); the comment feature is awaiting clarification.

Issue #399

---

dap-mode.el
dap-mouse.el
dap-ui-repl.el
dap-ui.el

watch expression doesn't work with code-debug. Looking at its [source code](https://github.com/WebFreak001/code-debug/blob/f2923480e45874324ca94badbe35c7ed80a5e172/src/mibase.ts#L622), it seems code-debug expects evaluateRequest's arg.context to be either "watch" or 'hover". Otherwise, it will assume "repl" context and pass the expression as is to gdb, resulting in error. I don't know who's at fault here. Anyway, here's the change that would make watch expression work.

Fix watch expression when using with code-debug

---

dap-variables.el
tests/dap-variables-test.el

Handle lists generically in `dap-variables-walk-launch-configuration':
previously, alists were detected and handled with -all? #'consp, which is not
ideal, as it precludes lists of lists from being expanded correctly; however,
worse than that, all other types of lists were automatically assumed to be
plists. This led to a bug if a list with an odd number of elements was to be
expanded: it would end in nil. Fix this by considering any list a normal list,
and by handling conses whose `cdr' is not a list specially instead.
Also support vectors correctly now (yield a vector if a vector is given).
Test the variable expansion code in tests/dap-variables-test.el, with a set of
tests exercising previous issues.

Improve variable expansion; add tests for it (fixes #346)

---

dap-gdb-lldb.el

Wonder if this will be useful for others. In embedded development environment, we usually use gdbserver to debug programs deployed in the target machine. This patch adds a configuration for gdbserver.

add support for gdbserver

---

dap-mode.el

Note especially the breaking change to `dap--make-response'' api. I have grepped the codebase for references to that function and didn't find any, however there may be third party plugins (official?). The only place in the dap protocol where the *client* gets to make a response is with "runInTerminal".

Implement :console "integratedTerminal"/"externalTerminal"

---

dap-netcore.el

This PR implements DAP support for projects on .NET core, using the [netcoredbg](https://github.com/Samsung/netcoredbg) debugger.
TODOS:

Add preliminary netcoredbg support

---

CHANGELOG.org
dap-lldb.el

The documentation says that the :type for both 'attach' and 'launch'
requests must be 'lldb-vscode'. (though it appears to work even when
the :type is wrong...)
An added benefit is that we no longer have any naming conflicts with
the dap-gdb-lldb's lldb debug adapter, which has :type 'lldb'.
----
#

[dap-lldb] Change :type to lldb-vscode, per the docs

---

dap-launch.el
test/dap-test.el

We already sanitize comments from JSON.  Let's also strip trailing commas.  I happen to have launch.json with trailing commas, which is out of my control at my workplace.  Furthermore, VSCode happily ingests these trailing newlines in the "JSON" launch configuration.  Emacs' DAP-mode should handle such "JSON" as well.
The regex works by finding any commas, followed any number of whitespace or newlines, followed by a closing brace or bracket.  The non-comma characters are placed in a separate regex group (2), so that they can replace the full match and only strip the comma itself.
With a file like the following
```
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: …
```

Strip trailing comments from launch.json

---

dap-launch.el
test/dap-test.el

The old regex was missing a significant number of legitimate spaces per the JSON spec: https://spec.json5.org/#white-space.  In effect this meant, we wouldn't strip trailing commas that were followed by these valid characters.  Make the regex exhaustive.
I'm sprinkling all the relevant space characters in the tests as defined by the spec to ensure our regex catches them all.
NOTE: if you try manually testing `dap-launch-sanitize-json` in `json-mode` or `js-mode`, you're gonna have a bad time.  Test this stuff in `fundamental-mode` if you find yourself so inclined...

Improve the "trailing-comma" regex

---

dap-mode.el

I'm using gccemacs with Straight.el. I noticed that this
``` emacs-lisp
-lambda ((session &as &dap-session 'name 'thread-states))
```
expanded to something like
``` emacs-lisp
(session input0)
(--dash-source-1018-- session)
(&dap-session
(car-safe
(prog1 --dash-source-1018--
(setq --dash-source-1018--
(cdr --dash-source-1018--)))))
(--dash-source-1019--
(car-safe
(prog1 --dash-source-1018--
(setq --dash-source-1018--
(cdr --dash-source-1018--)))))
```
which doesn't make sense.
Using `eval-and-compile` seems to make it expand to what we would expect.

Use eval-and-compile for `dash-expand:&dap-session'

---

README.org

I think the CI has moved from `Travis CI` to `GitHub actions`?

Update CI badge.

---

dap-variables.el

I recently hit this issue when trying to launch `dap-debug`.  Attempting to read from `.vscode` hit errors when trying to read the value `t`.  Instead of returning `t` when a file exists, return the actual file.
https://github.com/emacs-lsp/dap-mode/commit/9ad62ea562f3651bda3f6adb94d3274811147ec9#r43781039

Fix `dap-variables-find-vscode-config`

---

docs/page/configuration.md

I have added an update for rust. Rust strings is not built up around end escaping strings with \0. There for a native debugger like GDB will not show strings correctly in the Locals area when stepping through a debugging session. Rust has a tool for this which is basically some python formatters wrapped around gdb. All this is shipped with the rust toolchain when installing rust, so rust-gdb is on the PATH and ready to be called.
This brings me to my update of the configuration: add a gdbpath that tells the debugger to use rust-gdb instead of the plain version of gdb.
I have added this configuration so others can enjoy using dap mode while coding rust.

Added rust specific example setting

---

dap-mode.el

When the `no-select` option is passed to `dap-go-to-output-buffer` the default window isn't changed (it is not set to the window containing the output buffer). This PR explicitly resizes the window with the output buffer even when the default window remains set to something else.

Specify window to resize rather than relying on the current window

---

dap-go.el

If the :args field is already present in a given configuration, the
code tries to call `split-string` on that field, which is appropriate
to do once but will fail on subsequent calls, such as those
encountered when running `dap-debug-last`. Changing the conditional
here from a nil check to a `stringp` check worked for me.

dap-go: fix type error when splitting :args field

---

dap-launch.el
dap-python.el

- Set :host and :debugServer instead of :dap-server-path for attach requests.
- Read launch config using 'vector for json-array-type to preserve structure of
pathMappings across json-encode for the subsequent attach command.

Attach to remote Python (debugpy) adapter

---

dap-mode.el
docs/page/features.md

`dap-debug` now respects a `:compilation` option, which is a pre-compile step as
a `compilation` shell command (as discussed on discord with @yyoncho). This is
more of a POC and probably needs more refinement:
----
#

:compilation for `dap-debug`

---

dap-python.el

Symbols inside consts dont't need to be quoted and nil is not a valid value for the string type

Fix custom type mismatches

---

dap-go.el

Version 0.15.0 of vscode-go does not handle maps correctly, adding nulls to
them. This bug is fixed in version 0.22.1, so bump it in `dap-go-setup`.
The layout of the extension changed: the executable that needs to be run is no
longer goDebug.js, bug dist/debugAdapter.js. As such, users will need to
manually update `dap-go` using `C-u dap-go-setup`.
Fixes #399.
@yyoncho as noted in the second paragraph, this is a breaking change. This is unavoidable though, as currently `dap-utils` doesn't version vscode-downloads. How should this be handled?

`dap-go': bump vscode-go version

---

dap-hydra.el
dap-mode.el

This is to fix https://github.com/emacs-lsp/dap-mode/issues/54
1. I used `-if-let*` instead of a bunch of nested `-if-let`s.  I feel this made the code much easier to read, at the expense of better error messages.  I'm open to changing it if you think the better error messages are worth it.
2. I didn't add any tests.  I did briefly glance at the tests, but I didn't find one testing `dap--go-to-stack-frame` which I would have liked to copy.  Let me know if you have any pointers on how to write some good tests.
4. I have only tested this with `dap-lldb`.
3. I added it to the hydra under the "Switch" section rather than the "Stepping" section.  I kind of wanted to put it to "Stepping", so that it would be easier to invoke, but it seemed like it fit better for the switching (given that's …

Add dap-up-stack-frame and dap-down-stack-frame

---

dap-gdb-lldb.el

This allows to avoid `~` related issues when looking for the target
program in a parent/cousin directory (such as out of source builds)
Example : 
```
Warning (emacs): Initialize request failed: Failed to load MI Debugger: /home/USER/project/src/bin/~/project/src/bin/target.rs: Aucun fichier ou dossier de ce type. (from file-exec-and-symbols "/home/USER/project/src/bin/~/project/src/bin/target.rs")
```

Use `expand-file-name` for gdb-lldb targets

---

dap-cpptools.el

This custom allows to test, or definitely change the version of the
vscode extension. Currently the last tagged version is "1.5.1". The
default value stays "0.29.0" as "1.5.1" hasn't been thoroughly
tested.

Add custom variable for cpptools extension version

---

dap-mode.el

Fixes two small typos that I ran across when configuring `dap-mode`. Thanks for writing such a cool package!

spelling/grammar fix in `dap-terminated-hook` docstring

---

dap-cpptools.el

It currently checks if mono-mac exists, then attempts to set file modes on the linux mono

 dap-cpptools-setup set file mode on mac mono

---

dap-python.el

This will fix https://github.com/emacs-lsp/dap-mode/issues/490
`Python :: Run pytest (at point)` will work for class methods, e.g.
```python
class TestClass:
def test_method(self):
assert True
```

ensure pytest at point works with class methods

---

dap-python.el

After #503 was merged I could run dap-debug and select the template, but binding `dap-python-debug-test-at-point` directly did not.
At first I got the error that the template is not a string and then that the templates doesn't have `:type` (which it did, it was just wrong and the error was misleading).
Fortunately I was able to fix those myself.

make dap-python--debug-test-at-point work

---

dap-ui.el

This resolves #462.
If a user starts `dap-debug`, dap-mode creates a set of icons used to do common debug actions (step, continue, etc). These icons are created using `propertize` to make the text that displays the images on a background.
The existing setting uses the background color from the `fringe` face to set the background of the icon. The return value for the `face-attribute` function is not guaranteed to be specified. When the `:background` is unspecified, the space is made for the icons but nothing is displayed.
This PR defines a face to control the background color used for the debug icons. It defaults to using the background color defined in the `fringe` face, but will inherit from the `default` face if the `:background` attribute is unspecified in `fringe`.

dap-ui: Fixed issue where control icon background was unspecified

---

dap-ui.el

When provided by the debug adapter server, add the instruction pointer of each frame alongside its name in the `*dap-ui-sessions*` buffer.
For instance, the [SWI-Prolog debug adapter](https://github.com/eshelyaron/debug_adapter) reports for each frame exactly in which instruction pointer or stage the frame is stopped.
Here's an example of how the sessions tree looks with this addition:

dap-ui: Display `instructionPointerReference` when available

---

dap-unity.el
docs/page/configuration.md

Adding support for Unity (game engine) debug adapter.
Known Issues :
* Adapter will often fail to download from the vs marketplace requiring manual intervention.
* The adapter attempts to use DAP events that are not yet configured in dap-mode. This results in some "missing event" spam in the Messages buffer. The adapter is still very much usable, and the missing events can still be addressed in the future.

Added configuration for Unity debug adapter

---

dap-hydra.el

This was discussed on Discord. The existing debug commands in `dap-hydra` do not kill the current debugging sessions, which leads to them piling up if the user isn't aware. In my case, it made emacs fill up my memory and crash.
The command that should be used if the user isn't interested in the old sessions is `dap-debug-restart`. This PR adds it to the hydra. `dr` was already taken, so I arbitrarily set it to `ds`. This can, of course, be changed. The same goes for the description. 
Maybe the description should contain some information that this is usually what you want if you're inside a debug session? I don't know how to express it succinctly though.

Add dap-debug-restart to dap-hydra

---

dap-netcore.el

- add update netcoredbg function
- fix finding correct link for install or update
- add ability to use system global netcoredbg
- improve launch configuration
See https://github.com/emacs-lsp/dap-mode/issues/555
Have been tested on fsharp project and on csharp project

Improve netcoredbg

---

dap-netcore.el

Fix runtime error. Add missing parameter to `string-match-p` clause.
This PR fixes an error/regression introduced in https://github.com/emacs-lsp/dap-mode/issues/440 for GNU/Linux users.

Fix error intstalling netcoredb on GNU/Linux

---

dap-netcore.el
docs/page/configuration.md

- install netcoredbg without libxml2 support fixed
- upgrade without previous directory (or after upgrade error) fixed
- documentation updated

fix netcoredbg install without libxml2 support

---

dap-mode.el

As a consequence, it always used to return nil.

Fixed plist-get that had arguments swapped

---

dap-kotlin.el

The absolute minimum configuration for using the [Kotlin Debug Adapter](https://github.com/fwcd/kotlin-debug-adapter) to debug Kotlin code. For some reason, [lsp-kotlin already has a variable for debug adapter path](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-kotlin.el#L80), so reusing that one.
Currently only launch-requests are supported, which is a huge step forward from nothing. Future work may target attach requests as well, but I never use that, so would require some additional research from me to implement.

Bare minimum Kotlin Debug Adapter setup

---

dap-gdb-lldb.el

This fixes #601. This fix may be removed once https://github.com/WebFreak001/code-debug/issues/344 is fixed, though I'm not sure whether 'prettyPrinters' isn't even the better default.

Set 'valuesFormatters' to 'prettyPrinters' as default for dap-gdb-lldb

---

docs/page/python-poetry-pyenv.md

Not much, but could save someone's sanity one day. Importantly, this guide adds the vital step of running `poetry config virtualenvs.in-project true` during setup.

Python poetry + pyenv debugging tutorial

---

dap-dlv-go.el
docs/page/configuration.md

Add dlv-go debug adapter that uses delve debugger directly instead of current solution that based on vscode debug adapter.
Fixes #318

Add alternative go debug adapter

---

mkdocs.yml

Add missing link for https://github.com/emacs-lsp/dap-mode/pull/605
LSP-mode PR after this!

Add link to python tutorial

---

dap-mode.el

I often debug java projects with a stack depth of a couple of thousand frames. stepping is slow in this configuration, since the server gets asked for all of these frames on each step. making the number of requested frames configurable fixes that for me when I set it to a reasonable value. The stack trace in the session list is unaffected, so you can still access all the other frames.

Make number of stack frames to request when stopped configurable

---

dap-go.el

Hi, 
I try to download the extension with `dap-go-setup` but result in an empty folder. Update the extension version fixes this issue for me. Probably the old one is deleted for some reason.
I'm on Ubuntu 18, BTW.
Could you kindly take a look at the compatibility of this extension version?
Thank you!

dap-go: upgrade extension version

---

dap-cpptools.el
dap-utils.el

- Update the default version for `cpptools` to the latest
- Fix the path of the `OpenDebugAD7` binary in new version, it has changed from `extension/debugAdapters/OpenDebugAD7` to`extension/debugAdapters/bin/OpenDebugAD7` 
- Make new binaries executable

dap-cpptools: Update to v1.9.8

---

dap-codelldb.el

- Add a custom variable `dap-codelldb-extension-version`
- Upgrade version from 1.6.1 to 1.7.0

dap-codelldb: Upgrade from v1.6.1 to v1.7.0

---

dap-utils.el

This will fix #621. It seems the require calls must be at top level of the file for compilation of macros to work.

In dap-utils.el move require of xml and dom to top level

---

dap-kotlin.el

Configuration for dap-kotlin for attaching to an already running debug process. Set some sane defaults as well, and made a template to be able to attach to an already running process with default settings (localhost at port 5005).

Debug attach configuration for dap-kotlin

---

dap-dlv-go.el

Due to incorrect usage of `-when-let`, "Test function" was not working
as expected. Fix the usage of `-when-let` to correctly update `:args`.

dap-dlv-go: fix an issue with test current function

---

.github/workflows/test.yml
Makefile

We aren't using `DAP-GENERAL`, `DAP-CLIENTS` ... variables, I guess we can remove it?
Add `lint` and `checkdoc`, but left unused for now.

test(makefile): add lint and checkdoc entries, remove unused variables

---

docs/page/configuration.md

Add more information about substitute path usage. Improve trouble
shooting. See https://github.com/emacs-lsp/dap-mode/issues/630

dap-dlv-go: improve documentation

---

dap-mode.el

This is a proposal to filter stack traces in `dap--select-thread-id`.
Instead of jumping to the first stack trace in the list, filter them checking if `path` exists and jump to the first stack trace in the filtered list. Fall back to the original `stack-traces` if the filter produces an empty list.
This, I found, is especially useful for exceptions in eg: `lldb-vscode` where the first elements in  `stack-traces` have no valid `path`. This patch allows `dap` to at least open a buffer visiting the first valid `path` in the list and highlight the line that triggered the exception.

Prefer stack traces with a valid path

---

dap-mode.el

After 5e449c8 dap--get-path-for-frame expects debug-session.

Fix dap--select-thread-id after dap--get-path-for-frame change

---

dap-mode.el

Use 'cwd' and 'program' arguments only if they exist

---

dap-python.el

If using a python project structure, simply debugging the current file without setting cwd results in paths being different from regular execution.
For example:
myproject/src/main.py
myproject/src/lib.py.
If main.py imports lib.py as src.lib,
and the user debugs main.py while looking at the file, it will crash
instantly if cwd is not set.

Debug template for current file and root cwd

---

dap-mouse.el

The documentation for `tooltip-functions` says
```
Each function is called with one argument EVENT which is a copy
of the last mouse movement event that occurred.  If one of these
functions displays the tooltip, it should return non-nil and the
rest are not called.
```
Since `dap-tooltip-tip` is prepended in a global variable `tooltip-functions`, and it always return an empty string, which is truthy value in elisp, therefore it preventing every other tooltip-functions a chance to be run.
This PR fixes that.

Fix #314. Give other tooltip-functions a chance to run.

---

CHANGELOG.org
dap-codelldb.el
dap-gdb-lldb.el

fixes #467
Note: Will break any existing `launch.json` files and configurations using `codelldb` or `lldb` as type names.

Refactor debug provider names

---

dap-codelldb.el
dap-cpptools.el

- Bump version v1.9.8 ➡️ v1.11.5
- Check for the architecture to download the right extension 
- Bump version v1.7.0 ➡️ v1.7.4
- Check for the architecture to download the right extension

`cpptools+codelldb`: Updates, Better detection of the architecture

---

dap-launch.el
dap-mode.el
dap-tasks.el
dap-utils.el

The idea of this PR was initially to just handle [`preLaunchTask`](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes), which is a more robust, vscode-native version of `dap-compilation` for running tasks before a debug configuration. It shortly spiraled into the current PR, which I don't think goes _too_ far in terms of support.
It aims to be much more in line with vscode, and should be able to handle many more setups ootb.
Straightforward, it's used in `dap-tasks` and `dap-launch`.
Correctly handles tasks specified in a debug config's `preLaunchTask`. If no task is found matching the name, the config errors (much as it would in vscode). Down the line, `dap-compilation` could potentially be removed; but as it stands currently it actually takes precedence (so as to …

Add support for VSCode Tasks

---

dap-mode.el

Change the construction of the command to run the debug adapter with so that it properly escapes the arguments.
Fixes #684

Fix paths containing spaces

---

dap-node.el
dap-utils.el

Linked to: https://github.com/emacs-lsp/dap-mode/issues/554
Donwloading node-debug2 from VSCode Marketplace does not work. But the extension is available on Open VSX registry: https://open-vsx.org/extension/ms-vscode/node-debug2
This PR add support to download extensions from Open VSX registry and change `dap-node-setup` to use this feature.
Currently, direct download of the latest version of extension is not possible (https://github.com/eclipse/openvsx/issues/507). So it's down in 2 steps:
- query API (https://open-vsx.org/swagger-ui/index.html) to get metadata of extension and extract download URL
- download extension
PS: in addition to the technical difficulties related to VSCode Marketplace downloads, using Open VSX seems to be better from a legal point of view (according to …

Download node-debug2 from Open VSX registry

---

dap-utils.el
test/dap-test.el

Trying to debug a project with this [launch.json](https://github.com/ansible/ansible-language-server/blob/main/.vscode/launch.json) failed with a "JSON Readtable error".
I investigated the error and found that `json-utils-sanitize-json` does not remove the trailing comma on line 20 because the regexp does not correctly handle the case where there is only comments between comma and "]".
Rather than trying to add this case to the regexp, this PR splits the regexp in two and changes `json-utils-sanitize-json`  to run in 2 passes:
- first, remove comments
- second, remove trailing commas
This should make `json-utils-sanitize-json` more robust against this kind of cases.

Improve json-utils-sanitize-json

---

dap-dlv-go.el

With universal argument (C-u) you can edit command before run it in vterm.

dap-dlv-go: add ability to change command before run in vterm

---

docs/page/configuration.md

Provide information about latest changes and about `:buildFlags`

dap-dlv-go: update documentation

---

dap-ui.el

I found the default position of the dap-ui controls toolbar interfered with the top line of my preferred layout, so this PR turns the position of the controls toolbar into a customizable variable `dap-ui-controls-screen-position`. The variable accepts, as a value, the positioning functions used by `posframe`.
For example:
`(setq dap-ui-controls-screen-position #'posframe-poshandler-frame-top-left-corner)`
will position the controls toolbar in the top-left corner of the screen (my preference).
The default value remains `#'posframe-poshandler-frame-top-center` so current users will not be affected.

Add M-x customize parameter to set the screen position for the controls toolbar

---

dap-kotlin.el

It seems like a default for `projectRoot` can be quite useful in launch-type sessions as well. This makes it easier to make general debug templates for running/debugging tests 🙂 
```emacs-lisp
(dap-register-debug-template "Kotlin run tests with launcher"
(list :type "kotlin"
:request "launch"
:mainClass "org.junit.platform.console.ConsoleLauncher --scan-class-path"
:enableJsonLogging t
:jsonLogFile "/Users/marie/jsonlog.txt"
:noDebug nil))
```

Add sane default for projectRoot in Kotlin launch session

---

dap-magik.el

Support for Smallworld/magik. Requires https://github.com/emacs-lsp/lsp-mode/pull/3843
Provides:
* Attachable debugger to active Smallworld/magik session.

Support for Smallworld/magik

---

dap-kotlin.el

After putting these in my own debug templates and similar for a while, I thought it would be great to be able to configure them using variables in dap-kotlin instead. This makes it possible to log the servers internal logs to a file. That is useful for debugging issues with the server/debug-adapter.

Add Kotlin Debug Adapter logging arguments as variables

---

dap-ui.el

This pull request enables repl input history to be saved across session on a per-type basis. For example, for `:type python`, the history is saved in a file called "dap-ui-repl-python-history".
The save path can be customized and defaults to `user-emacs-directory`.

dap-ui: save repl input history

---

CHANGELOG.org
dap-gdscript.el

Godot 4.0 includes support for the debug adapter protocol.
Support should be added, nvim already supports it: [Godot gdscript](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#godot-gdscript)

add support gdscript/godot4 DAP debugger

---

.github/workflows/test.yml
CHANGELOG.org
Eask
dap-mode.el

Same idea as https://github.com/emacs-lsp/lsp-mode/pull/4126.

fix(dap-mode.el): Drop support for 26.x

---

docs/page/configuration.md

dap-mode with Kotlin is sadly not as simple to setup as the Java one, nor is it as feature complete. From what I heard, many people are missing some documentation on how to setup, how it works etc. This is what I have done here. Some info on useful things like running JUnit tests is also covered. This is not really covered that many places, so I think it would be super useful to have the information in a place like this! 🙂 Might also get more interest in debugging and running Kotlin code in Emacs 🙂 (to be honest, I rarely use debuggers, but find it super nice to be able to run tests like this inside Emacs!)
A little bit unsure on the formatting, but tried to copy the style of what I could find...

Add Kotlin documentation to configuration guide

---

dap-ocaml.el
docs/page/configuration.md

This PR adds support for OCaml through the newly revived [earlybird](https://github.com/hackwaly/ocamlearlybird) debugger.

Add support for OCaml through Earlybird

---

dap-utils.el

This change fixes this error when running `(dap-node-setup)`: `url-insert-file-contents: https://open-vsx.org/api/ms-vscode/node-debug2/latest/: Not found`
The problem was that the OpenVSX URL template string had a trailing slash, which is not handled by OpenVSX's Registry API Controller: https://github.com/eclipse/openvsx/blob/master/server/src/main/java/org/eclipse/openvsx/RegistryAPI.java#L348
I can't really find a blame in the OpenVSX repo which could've caused the extraneous trailing slash to stop working. Maybe the update to Java 17?
As you can see, there's no trailing slash at the end, so the route doesn't get mached in the controller and causes a 404 Not Found.
Just removing the slash does the job and `(dap-node-setup)` runs successfully.
References:
- …

Fix 404 error when attempting to download OpenVSX extensions

---

dap-python.el
docs/page/configuration.md

This is modified version of https://github.com/emacs-lsp/dap-mode/pull/384
I've fixed previous PR, so it works with `debugpy` now.
Didn't check for ptwsd though.

dap-python: Support attach to an existing process

---

dap-mode.el

dap-delete-session
fix: output-buffer is not deleted

delete-session output-buffer fix

---

dap-mode.el

This is a fix for a bug I erroneously introduces in PR #754 . 
The function `dap--buffers-w-breakpoints` was returning a list of files names instead of a list of buffers. This in turn broke the `dap--switch-to-session`.
With this fix, the list of buffers is inferred by the first marker of the first breakpoint found for each file.

fix: get list of buffers (not files) with breakpoints

---

dap-ui.el

This defcustom controls the depth to which dap-ui-sessions expands by default

Add customization option to control expand depth for dap-ui-sessions

---

dap-firefox.el

I think VSCode extension requires absolute paths from file selectors. With relative path dap-mode does not work. Here is there warning it gives me:
(Warning (emacs): Initialize request failed: The "file" property in the launch configuration has to be an absolute path)

Fixes the warning about file property has to be absolute path

---

CHANGELOG.org
dap-gdb.el

Fixes <https://github.com/emacs-lsp/dap-mode/issues/790>.

Support real GDB

---

dap-mode.el

This PR comprises two commits:
1. the first fixes the pitfall described below, reported by @cpitclaudel;
2. the second looks at some opportunities for simplification spotted while looking around for places that do printing.
The output of printing functions (including `prin1` and, by extension, `format` with a `%s` sequence) is affected by a set of [output variables](https://gnu.org/s/emacs/manual/html_node/elisp/Output-Variables.html) that both end-users and libraries can tweak.
This is fine in the more common use of these functions to format messages, but the problem is that the same functions are also the most convenient way to serialise/persist data.
Serialisation should be robust to non-default values of `print-length` and `print-level` in particular, as setting these to small numbers …

Protect breakpoint persistence from print-* vars

---

dap-ui.el

While setting up dap mode in emacs, noticed that in dap-ui-overlay-priority description there was a typo. Fixed typo with this PR.

Changed prioirty typo to priority

---

dap-hydra.el

Stop the hydra to edit text normally.
I think this feels more "natural". `dap-debug-edit-template` brings up another buffer for editing, exit the hydra to free keys for that purpose.

dap-hydra: make dap-debug-edit-template exit

---

dap-python.el

The `:type` of the debug template "Python :: Run pytest (at point)" should match the "LANGUAGE-ID" argument of the function `(dap-register-debug-provider)`, otherwise the "PROVIDE-CONFIGURATION-FN" is not called (and all tests in the current buffer are run, instead of just the test function at point).
I also humbly suggest to edit the doc string of `(dap-register-debug-provider)` so that it explicitly references the name of the property `:type` of the plist "CONFIGURATION-SETTINGS" in `(dap-register-debug-template)`. I'm not providing a MR for this because it's entirely possible that the problem is actually me not understanding what's going on here :slightly_smiling_face:

Change the :type of pytest-at-point debug template

---

dap-codelldb.el
dap-cpptools.el
dap-gdb-lldb.el
dap-utils.el

This PR adds a function to get the latest release from Github. The current `dap-utils-get-github-extension` requires an explicit version number, I've changed it to be optional (backward compatible), and when the `version` is set to nil, it gets the latest version.
TODO: Make use of the new feature to get the latest version of extensions.

Feat/get latest GitHub release

---

.github/workflows/test.yml
Eask
dap-mode.el

See https://github.com/emacs-lsp/lsp-mode/pull/4720.

feat: Drop Emacs 27.x

---

dap-ui.el

Fix keyword arguments for `treemacs-define-variadic-entry-node-type`
