dap-mode.el
When using dap-mode, I find that the *out* and *stderr* buffers accumulate quite
rapidly. This option uses the previously created buffers if they are found.
=> Name output and stderr buffers according to session name, reuse if they exist

README.org, dap-node.el
=> Add js debugger using VsCode built-in Node debugger

dap-python.el
Similar to `spacemacs` `spacemacs/python-execute-file` https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/python/funcs.el#L437
we should pick the appropriate python executable, taking python virtual env into concern.
I simply added a method, that is a copy of https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/python/funcs.el#L116
=> [imp] check for python env, when searching for executable

dap-elixir.el
=> Elixir: Fix requireFiles incorrectly include folders in lib

dap-mode.el
`compile()` allows only one subprocess to run simultaneously unless renaming the buffer name.
Using `compilation-start()` instead can run multiple subprocesses and use arbitrary major mode.
Also, we can now get more suitable buffer name and log messages like "Debug Adapter started at ..." rather than "Compilation started at ...".
=> Allow multiple debug sessions when using :program-to-start

dap-mode.el
I found deleting session(s) may fail trying to delete the process dead already.
We should consider the follwing things:
- Response to `configurationDone` request may be processed after the process is terminated
- The process is not running in `failed` state as well as `terminated` state
The fix seems to work well, but I'm not sure whether `dap-session-changed-hook` should be run in `dap--send-configuration-done()` even if the process has been terminated.
=> Fix failures trying to delete the process dead already

dap-python.el
#164 
I assumed module was also a file path.
=> Support paths with spaces dap-python

dap-java.el
=> (dap-java) Force console to internalConsole

README.org, dap-go.el
fix to go debug mode:
- fix to dap-go.el
- instructions readme.org
=> #188 fix to go debug mode

README.org, dap-go.el
=> Go remote mode fixes

README.org, dap-go.el
updated readme and pass args as list.
=> fixes issues #205 and #208

dap-java.el
To keep this simple, `dap-java-use-testng` flag is added. When set to
a non-nil value, `dap-java--run-unit-test-command` builds the programm
list to run TestNG; default is nil to run JUnit and keep the existing
behaviour unchanged.
Additionally, the directory where TestNG generates reports can be
customized via `dap-java-testng-report-dir`
=> Add support for running TestNG tests

README.org
I just fixed the link.
Thank you for all the great work!
=> The link to "configuration" was pointing to gallery

dap-python.el
Minor changes for more consistent template names.
=> Python debug template names

dap-mode.el, dap-ui-repl.el, dap-ui.el
Allow REPL windows to be shown when enable autoconfigure mode
=> dap-features->windows: add REPL window

dap-ui.el
Fixes #230, depends on https://github.com/emacs-lsp/lsp-treemacs/pull/42
=> Expand first level of dap-ui-locals (#230)

dap-ui.el
Reverts emacs-lsp/dap-mode#286
=> Revert "Expand first level of dap-ui-locals (#230)"

dap-go.el
=> Fix publisher used in dap-go-setup

docs/page/configuration.md
=> Fix documentation for new publisher

dap-java.el, dap-python.el
https://github.com/emacs-lsp/lsp-mode/issues/1751
=> Use lsp-protocol

dap-launch.el, dap-mode.el, dap-ui.el, dap-variables.el
PR for #324.
The change to dap-ui.el was already merged, and I have no idea how to remove it. I am still a bit new to git.
=> launch.json support for dap-mode

docs/page/features.md
I documented DAP's launch.json support in this feature branch.
=> Document launch.json support

dap-ui.el
1. fix read string syntax error #329 
2. show variable in Expression buffer in one line #328
=> fix small issues

dap-launch.el
=> In dap-launch-find-launch-json, check if it exists before returning

dap-php.el
This patch does the following minor changes:
* Don't place brackets on the newline.
* Add line between each operation to better seeing it.
=> Minor changes for dap-php.

dap-mouse.el
Fixed warnings for `dap-mouse`.
=> Fixed warnings

dap-utils.el
* Add version option
* Add callback to call after download
=> Add callback and version do download vscode extension util

dap-netcore.el
These are the changes what lived in the comments of the original PR #138.
=> dap-netcore: Fix Windows install, and add "Attach to process"

dap-mode.el, dap-mouse.el, dap-ui.el
Make dap's hover tooltips not broken. Please see the REVIEW comments also.
=> Bugfix/dap mouse broken#367

README.org
Add discord badge/link to README file.
=> Add discord badge to README

dap-mode.el, test/windows-bootstrap.el
Same PR with https://github.com/emacs-lsp/lsp-mode/pull/2614
=> Fix CI by removing dash-functional 

dap-mode.el, dap-ui.el
=> Support capabilities event

docs/page/configuration.md
broken by switch from master to main
=> Fix documentation links to llvm github

dap-mode.el, docs/page/features.md
=> Fix spelling error

dap-cpptools.el
Fixes https://github.com/emacs-lsp/dap-mode/issues/455
=> Fix mac related file permission issues

test/windows-bootstrap.el
Remove custom elpa path.
Same as PR, https://github.com/emacs-lsp/lsp-mode/pull/2908
=> Remove custom space

dap-python.el
=> drop '_' from test function/method prefix

dap-netcore.el
Hi. Thanks for this cool project!
I have spent some time to figure out how to use dap-netcore. After initial setup it works flawlessly. Maybe this PR can help someone to spare some time. 
P.S. I also think it's worth it to add `dap-netcore` into documentation. But I think it's the task for another PR.
=> improve dap-netcore out of the box experience

dap-netcore.el, docs/page/configuration.md
- improve netcoredbg install error messages
- add netcoredbg into documentation
=> Improve netcoredbg documentation

dap-mode.el
Reverts emacs-lsp/dap-mode#529
=> Revert "Fix dap--put-if-absent to allow unsetting keys"

dap-netcore.el
=> require dom

.github/workflows/test.yml
Simplify merge the two actions.
=> Use merged setup-emacs action

dap-ui.el
Allows the user to view and jump to breakpoints using completing-read
This was discussed on Discord. @yyoncho also suggested encoding the state of breakpoints with colors, which I'm all for. But I'm not sure how it should look, so taking suggestions there. Just a colored dot at the end of the string, maybe? Not familiar with how this would be done, but I guess that `dap-ui-breakpoints` is a good starting point.
There are some additions I want personally, such as using consult-preview to view the entire context of the breakpoint, as well as the ability to delete them with embark. However, that might be better suited for my personal config.
=> Add dap-ui-breakpoints-browse

dap-dlv-go.el, docs/page/configuration.md
Thanks @polinasok for tips in #603
=> Improve dap dlv go docs

dap-dlv-go.el
=> Fix go dlv exec

dap-dlv-go.el, docs/page/configuration.md
Add ability to debug current test function.
=> Add go test debug current function

docs/page/configuration.md
=> Add substitutePath to go docs

dap-mode.el
A lot of smaller debug adapters around the web does not support exception breakpoints, and a few I've tried even make the setExceptionBreakpoint request crash the adapter. (Example: some of these are assembly specific for 80s and 90s processors, like MOS). From what I can see in the specification of Debug Adapter Protocol, it is not necessary to send a setExceptionBreakpoints request if we do not have any. From the [specification](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized): "frontend sends a ‘setExceptionBreakpoints’ request if one or more ‘exceptionBreakpointFilters’ have been defined (or if ‘supportsConfigurationDoneRequest’ is not defined or false)"
While we could also make all adapters handle setExceptionBreakpoints, I think it makes more …
=> Don't make setExceptionBreakpoints request if filters would be empty

dap-netcore.el
Fixes #627 
Instead of use `lsp-workspace-root` try to predict root of local project for find correct `.dll` location
=> Fix for multiproject netcore solutions

dap-go.el, docs/page/configuration.md
=> Deprecate dap-go

dap-dlv-go.el
=> dap-dlv-go: parse env files on emacs side

dap-mode.el
=> Use "\" for paths on windows

dap-dlv-go.el
=> dap-dlv-go: add ability to test single subtest

dap-dlv-go.el
Experimental ability to choose go binary and execute it inside vterm. Then attach to it with delve. User can interact with program inside vterm buffer.
=> dap-dlv-go: experimental vterm integration

docs/page/configuration.md, docs/page/features.md
I had a hard time figuring out how to use dap-mode for Python. This pull-requests adds some og the required pieces.
=> Enhance documentation

docs/page/configuration.md
Hi. I'm new to dap-mode, and I found the instructions for the native debuggers a little sparse and out-of-date in places. After spending some time figuring out how they work, I've updated the documentation to (hopefully) make things clearer and explain the configuration options in more detail. HTH, Stu Perry.
=> Consolidate and update native debug instructions

dap-launch.el, dap-mode.el, dap-tasks.el
Fix a defcustom and function not known to be defined warnings.
=> Fix byte compiler and native compiler warnings
